### ISSUE TITLE
Theme shows no UI

### ISSUE THREAD

**Issue by cmalkus** [mmatyas/pegasus-theme-flixnet#1]
After selecting Flixnet theme the screen is black with a white box and input does not work. Below is the terminal output after selection:

```
[w] file:///home/pi/.config/pegasus-frontend/themes/pegasus-theme-flixnet-master/theme.qml:114: Error: Cannot assign JavaScript function to int
[w] file:///home/pi/.config/pegasus-frontend/themes/pegasus-theme-flixnet-master/Screenshot.qml:25:5: Unable to assign [undefined] to bool
[w] file:///home/pi/.config/pegasus-frontend/themes/pegasus-theme-flixnet-master/Details.qml:26:5: Unable to assign [undefined] to bool
[i] 12730 games found
[w] file:///home/pi/.config/pegasus-frontend/themes/pegasus-theme-flixnet-master/theme.qml:110: TypeError: Cannot call method 'next' of null
[w] file:///home/pi/.config/pegasus-frontend/themes/pegasus-theme-flixnet-master/theme.qml:110: TypeError: Cannot call method 'next' of null
[w] file:///home/pi/.config/pegasus-frontend/themes/pegasus-theme-flixnet-master/theme.qml:109: TypeError: Cannot call method 'prev' of null
```

Here is my Pegasus/Raspbian versions
```
Linux retropie 4.14.98-v7+ #1200 SMP Tue Feb 12 20:27:48 GMT 2019 armv7l
[i] Pegasus alpha10-128-g13b655a (2019-02-17)
[i] Running on Raspbian GNU/Linux 9 (stretch) (arm, eglfs)
```

**Comment by mmatyas** [comment]
Yes, the theme got a bit outdated with the recent changes, I'll update it when I have some time.

**Comment by iwubcode** [comment]
@mmatyas  - is there any documentation on what changes this theme might need to work?  I always thought it sounded pretty cool and wouldn't mind taking a stab at it if I can find some time.

**Comment by mmatyas** [comment]
This theme was originally a base for one of the tutorials, but at the moment that's also outdated :( I'd like to fix it and reorganize a few things eventually, but if you're interested [this post](https://retropie.org.uk/forum/topic/9598/announcing-pegasus-frontend/1025) tells the changes. There are also things like "remembering the game" which might need newer API functions. Hopefully I'll have some time soon to fix all the things.

**Comment by mmatyas** [comment]
Took a while but the theme got updated and should now work again.
